### ISSUE TITLE
Language suggestions

### ISSUE THREAD

**Issue by ghost** [dbohdan/embedded-scripting-languages#10]
* SGScript (sgscript.org)
* Jinx (http://www.jinx-lang.org/index.htm)
* Dyon (https://github.com/pistondevelopers/dyon)
* Gluon (https://github.com/gluon-lang/gluon)
* Mond (https://github.com/Rohansi/Mond)

**Comment by dbohdan** [comment]
Thanks for your suggestions!

I've added SGScript. Each of the rest of the languages has something interesting about it, but my first impression is that they are not mature enough to use in a project unless you are also working on the language itself. I've prepared list entries for those languages (below) and set up a reminder to give them another look in six months. You can ping me to check any of them sooner through this issue. I'll keep it open until I decide whether to include each language.

| Project name/link | Implementation language | GC | License | Notes |
|-------------------|-------------------------|----|---------|-------|
| [Dyon](https://github.com/pistondevelopers/dyon) | Rust | None (Rust-style [lifetimes](http://www.piston.rs/dyon-tutorial/lifetimes.html)) | Apache License 2.0 or MIT | Has an optional, succeed-by-default static type system. |
| [gluon](https://github.com/gluon-lang/gluon) | Rust | Tracing | MIT | Statically typed. Inspired by Lua, Haskell, and OCaml. Each executing gluon thread gets a separate heap. |
| [Jinx](http://www.jinx-lang.org/) | C++ | Ref. counting | MIT | Designed for use in realtime applications such as video games. |
| [Mond](https://github.com/Rohansi/Mond) | C# | CLR's GC | MIT | Has sequences (generators) and async/await for concurrency. Implements prototype-based OO. |

**Comment by sauer2** [comment]
That  seems reasonable. thanks for your addition.

**Comment by dbohdan** [comment]
https://github.com/lemon-lang/lemon

**Comment by OvermindDL1** [comment]
[Shine](https://github.com/richardhundt/shine).

**Comment by dbohdan** [comment]
@OvermindDL1 Thanks!

**Comment by jespa007** [comment]
Zetscript programming language (quite new).

ZetScript is a programming language and comes with and API that allows bind your C++ code into script side.

http://zetscript.org

**Comment by daniellandau** [comment]
https://github.com/totalspectrum/tinyscript

**Comment by mingodad** [comment]
Here is a new syntax on top of Lua/LuaJIT vm LJS https://github.com/mingodad/ljs it's a lexer/parser modification of the original Lua/LuaJIT languages and hence self contained.

There is also several projects ported to it for test/show purposes:
ljsjit at https://github.com/mingodad/ljsjit

ljs-5.1 at https://github.com/mingodad/ljs-5.1

ZeroBraneStudio port at https://github.com/mingodad/ZeroBraneStudioLJS

raptorjit-ljs at https://github.com/mingodad/rpatorjit-ljs

snabb-ljs at https://github.com/mingodad/snabb-ljs

premake5-ljs at https://github.com/mingodad/premake-core/tree/ljs

CorsixTH-0.62-ljs at https://github.com/mingodad/CorsixTH-ljs

**Comment by dbohdan** [comment]
@mingodad I've added ljs.

**Comment by dbohdan** [comment]
@daniellandau TinyScript looks too early in development to add yet. Please remind me to check it later if it matures.

**Comment by majj** [comment]
https://github.com/dop251/goja

**Comment by dbohdan** [comment]
Added Goja.  Since SGScript, Jinx, Dyon, Gluon, and Mond have all been added, I am closing this issue.  Please open a new issue if you want to submit a project.
