### ISSUE TITLE
PH7 - Embedded Implementation of PHP

### ISSUE THREAD

**Issue by symisc** [dbohdan/embedded-scripting-languages#16]
Consider adding PH7 which is an embedded, single C file implementation of PHP (compiler and VM). 
https://github.com/symisc/PH7

**Comment by dbohdan** [comment]
Thanks for the suggestion! I've seen PH7 before and was impressed by it, but I only include non-copyleft or limited-scope copyleft (e.g., LGPL) scripting languages on this list because that's what I find the most useful. PH7 will be among the first projects I add if I revise this policy.
