### ISSUE TITLE
Add Gravity

### ISSUE THREAD

**Issue by praisethemoon** [dbohdan/embedded-scripting-languages#17]
>Gravity is a powerful, dynamically typed, lightweight, embeddable programming language written in C without any external dependencies (except for stdlib). It is a class-based concurrent scripting language with modern Swift-like syntax.

[https://github.com/marcobambini/gravity](https://github.com/marcobambini/gravity)

**Comment by dbohdan** [comment]
Looks good to add. Do you use a tracing GC? https://marcobambini.github.io/gravity/internals/4_gc.html is empty.

**Comment by dbohdan** [comment]
Okay, it looks like they do. Added in 213d29553c17ac4babf9d58d05adb13fe6dc5bf8.

**Comment by praisethemoon** [comment]
Thank you!
