### ISSUE TITLE
Add HashLink (a Haxe bytecode VM)

### ISSUE THREAD

**Issue by zhao-huang** [dbohdan/embedded-scripting-languages#24]
[HashLink](https://hashlink.haxe.org/) ([available on Github](https://github.com/HaxeFoundation/hashlink)) is a virtual machine for [Haxe](https://haxe.org/). 
RST game [Northgard](http://store.steampowered.com/app/466560) use it.

| Project name/link | Implementation language | GC | License | Notes |
|---------------------|-----------------------------|-----|----------|--------|
| [HashLink](https://hashlink.haxe.org/) | C | Tracing (Lazy sweep) | MIT | A bytecode interpreter and baseline JIT-compiler (x86/x86-64 only) for [Haxe](https://haxe.org/). |

**Comment by dbohdan** [comment]
Added in 28de736. Thanks!
