### ISSUE TITLE
Add Umka

### ISSUE THREAD

**Issue by vtereshkov** [dbohdan/embedded-scripting-languages#48]
I have released Umka, a statically typed scripting language: https://github.com/vtereshkov/umka-lang

**Comment by dbohdan** [comment]
Thanks for the suggestion.  Added in a93276cd2d6e4d4c13a87ba526aca01b21f2a41b.

I think you should say in the readme that Umka's fibers are not M:N-scheduled.  The language looks like Go and one of the examples is called "Multitasking", so it makes you wonder what the green threading model is.

The logo resembles a cat.  Did you name the language after a cat named after a fictional polar bear? :-)

**Comment by vtereshkov** [comment]
@dbohdan  Thank you. Yes, I'll consider providing more details in the README. By the way, currently Umka uses reference counting, not a tracing garbage collection.

> The logo resembles a cat. Did you name the language after a cat named after a fictional polar bear? :-)

Exactly!

**Comment by dbohdan** [comment]
>Umka uses reference counting, not a tracing garbage collection.

Oops.  Fixed in eee74a1.
