### ISSUE TITLE
Consider Adding Falcon http://falconpl.org/ 

### ISSUE THREAD

**Issue by Eyadhanna** [dbohdan/embedded-scripting-languages#5]

**Comment by dbohdan** [comment]
Thanks for the suggestion. At a glance, Falcon has interesting features (tables, messages), but it isn't v1.0 yet, seems to lack ongoing development and has a licensing scheme that would make it harder to use than any other language on the list. (The GNU GPLv2 is, as the author says, too restrictive for an embedded scripting engine, and it would also be a pain to deal with an untested, long, copyleft custom license.) For these reasons, I am reluctant to add Falcon as it is right now.

That said, feel free to correct me on any mistakes I've made in this assessment or to suggest reasons to add Falcon regardless.

**Comment by dbohdan** [comment]
Added in 6aa0b13d03846749ef8727b717ab8fd2b3c40d51 after allowing strong copyleft.
