### ISSUE TITLE
Add GDScript (Godot Script)

### ISSUE THREAD

**Issue by Tyrben** [dbohdan/embedded-scripting-languages#57]
This language was invented to script procedures in the 3D engine Godot.
It's close to Python.

**Comment by dbohdan** [comment]
Can you use GDScript as a library outside of Godot?  This list is for open source scripting languages you can embed in your program.

**Comment by Tyrben** [comment]
Do you mean "is there a turnkey library of GDScript", or "does the licence allow to use it outside Godot"?
I didn't see any separated lib, so without coding it a little, you can't currently use it outside Godot.
And yes, the licence of this language is the same as Godot: CC-BY-4.0 License . Meaning you may use it outside Godot.

**Comment by dbohdan** [comment]
I meant if there was a library.  Since there isn't (yet?), I can't add it to the list.  You are welcome to reopen this issue once there is.
