### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by alexec** [dbohdan/embedded-scripting-languages#68]
I don't see any commits for 9 months.  The project was getting updates every 1-2 months up until then. Is the project abandoned?

**Comment by FrankStain** [comment]
@alexec why should one commit something in stable and complete repo?
There are a lot of cool, popular and stable stuff around here, where the last commit was made a couple of years ago.

**Comment by dbohdan** [comment]
Sorry, I am not currently maintaining my GitHub projects because I am quite sick. I hope to return to them when I get better.

**Comment by dbohdan** [comment]
#71

**Comment by dbohdan** [comment]
https://github.com/dbohdan/embedded-scripting-languages/issues/71#issuecomment-1664172741. We're back.

**Comment by alexec** [comment]
I’m sorry to hear your were sick and I hope you’re feeling better now.
