### ISSUE TITLE
addition?

### ISSUE THREAD

**Issue by oict18** [dbohdan/embedded-scripting-languages#69]
maybe add BASCOM from MCS-Electronics?  It's a compiled basic for AVR & 8051

**Comment by cubiclesoft** [comment]
https://github.com/dbohdan/embedded-scripting-languages#contributing

>  The VM, bytecode compiler, and standard library (if any) must have a free (libre) license.

BASCOM appears to be a commercial product.  It also doesn't appear to be embeddable nor appears to be a scripting language.  A scripting language runs without compiling code.  Embedding in this context does not mean embedded hardware but rather the ability to embed the language into another compiled language.  Lua is the classic example of this.  BASCOM does not appear to do either of those things.

**Comment by dbohdan** [comment]
@cubiclesoft is right. Sorry, this is not eligible. Closing.
