### ISSUE TITLE
Contributor wanted to help with PRs/issues

### ISSUE THREAD

**Issue by dbohdan** [dbohdan/embedded-scripting-languages#71]
I am looking for a contributor to resolve this repository's issues and PRs, since I am currently sick and unable to. I will give you contributor access to commit to this repository. You can resolve issues as well as add and update scripting languages independently. I have some requirements, which amount to "do the things I do":

* Add languages to the table with the correct name, URL, license, GC type, and something helpful in the "Notes" column. If a PR has missing information, fill it in yourself. Remove marketing speak from the notes.
* Make sure new languages that you add follow the rules in [Contributing](https://github.com/dbohdan/embedded-scripting-languages#contributing). 
* Do not change "Contributing". Part of value of this repository is that the projects listed are selected for being open source and maintained or mature.
* Write useful commit messages. Add/update one language per commit when reasonable. (See the commit history.)

Comment if you are interested.

**Comment by mwasplund** [comment]
@dbohdan I am willing to help review and complete some PRs while you are out.

**Comment by dbohdan** [comment]
@mwasplund Thanks for volunteering! :-) I have sent you an invite.

**Comment by mwasplund** [comment]
@dbohdan Thanks, quick question before I start to look at it. How do you feel about adding more columns to the table to indicate things like language type (OOP vs functional vs procedural) and type system (static vs dynamic)

**Comment by dbohdan** [comment]
Go ahead! I support adding columns. (Though maybe you could put some of these things in the same column, like OOP and typing discipline? Up to you.)

**Comment by dbohdan** [comment]
Also, feel free to push changes directly to the repository. You don't have to PR your own commits unless that is your preference.

**Comment by mwasplund** [comment]
I prefer creating PRs to allow others to provide feedback before merging the changes.

**Comment by simonmichael** [comment]
Thanks for this excellent list, and best wishes @dbohdan.

**Comment by mwasplund** [comment]
That is great to hear! Sorry, I have been a bit behind on this project, I also had medical issues that have been taking up a lot of my time. I would love to continue to contribute since I have an interest in the area. Feel free to @ mention me in PRs you want me to help review

**Comment by dbohdan** [comment]
Thanks! I am sorry about your medical issues. I sincerely hope you improve soon. Of course, you are welcome to keep contributing! I'll mention you in the upcoming generator PR and the issue before if I open one.
