### ISSUE TITLE
Feedback wanted: switching to a list format

### ISSUE THREAD

**Issue by dbohdan** [dbohdan/embedded-scripting-languages#78]
How would you as a user of this list feel about a switch from a table to a nested list format? Example: [before](https://github.com/dbohdan/structured-text-tools/tree/1cbaf96da3672ab97b05a248bbd1e744d1df5c0b#ini), [after](https://github.com/dbohdan/structured-text-tools/tree/37dc179f49758f1ffe3aff9b3159f7639e1916ee#ini).

**Comment by paulocoghi** [comment]
Visually, the table is more pleasant to the eye. But , on the other hand, the nested list allows more "rows", rows which would be extra columns on the "width limited" table.

My final vote would be that, so far as the data allows the table format, maintain it as a table.

**Comment by mwasplund** [comment]
My vote would be for table view. It allows for easy scanning of relevant properties to zero in on a language that will fit my requirements. It was what initially drew me to this project in the first place.

**Comment by dbohdan** [comment]
Closing this. Nobody has commented in favor. With the introduction of sorting (#83), we have a strong reason to stick to the table format.
