### ISSUE TITLE
Switch to generating README.md: what language?

### ISSUE THREAD

**Issue by dbohdan** [dbohdan/embedded-scripting-languages#79]
Since I switched [Structured Text Tools](https://github.com/dbohdan/structured-text-tools) and [Classless CSS](https://github.com/dbohdan/classless-css) from a `README.md` edited by hand to one generated from data files, I have found them easier to maintain. Alphabetical order no longer requires attention.  I was able to add a new feature, fully duplicating Structured Text Tools items in different categories, without worrying about the items falling out of sync. Based on this experience, I would like to switch this repo to a generator as well. It would make #67 easy to solve  (generate two files sorted differently). I think #67 needs solving to keep a growing list usable.

This leaves the question of the language and the data format. I am considering Python, Lua (LuaJIT?), and TypeScript (Deno). They are all popular languages, especially Python and TypeScript. A person interested in embedded scripting languages often knows at least some Lua. This is a consideration for making things easier for PR contributors. Using Lua would make this repo rank highly in the Lua category, which would expose Lua users to it. Would doing it on purpose be spam? I know Python better than TypeScript and TypeScript better than Lua.

I use Python with TOML in the [Structured Text Tools generator](https://github.com/dbohdan/structured-text-tools/blob/d8dc1ac173ceb85776b3dc87c12acea234c96079/render-template.py) and TypeScript with [qmail](https://en.wikipedia.org/wiki/Qmail)-style single-value files in the [Classless CSS](https://github.com/dbohdan/classless-css/blob/e3bd4df31d53f08ee32ba7b4c04eea96e8736db2/gen-readme.ts) generator. Lua could be its own data format.

@mwasplund Do you have a preference for what  language and data format (TOML, YAML, JSON, Lua, etc.) to use? As a committer, you will need to edit the data and run the generator. I don't know what OS you use. All three options are cross-platform, so the OS shouldn't be an issue. You can propose another language option, but mind that I am strongly biased towards sticking with these because they are widely used and widely available.

**Comment by mwasplund** [comment]
Let me make sure I am understanding the goal here. By using a data folder with individual sub folders for each language/runtime we can implement a script to scan those folders and load a known text/config file to build a root readme markdown file?

I believe this is the right direction to go for maintainability. I would also propose that we have deep links into the individual language sub-directories to have a high level summary in the property table in the root readme, but more in-depth examples, summaries, thoughts, status etc. in the individual config.

Aside: I would also like to add a strict "status" to possibly allow hobby projects or projects just getting started a chance to list their work and bring interest and not muddy the waters of more fleshed out projects that folks may be looking to incorporate into their own projects.

I prefer TOML personally (and have written my own config language based on it), but JSON + TS is so ubiquitous it is a great choice simply for lowering the barrier to entry.

**Comment by paulocoghi** [comment]
I vote for JSON + JS for the same reason as Matthew, for lowering the barrier to entry.

**Comment by dbohdan** [comment]
> Let me make sure I am understanding the goal here. By using a data folder with individual sub folders for each language/runtime we can implement a script to scan those folders and load a known text/config file to build a root readme markdown file?

Not quite. I didn't mean to suggest data subfolders. My primary goal is to generate `README.md` from data of any structure, perhaps a single file. A secondary goal is to solve #67 by generating two tables: one sorted alphabetically, like now, and one sorted by implementation language. They could be in the same file (`README.md`) or different files. The structure of the data directory doesn't have to reflect this. The data can look like [structured-text-tools/data/projects.toml](https://github.com/dbohdan/structured-text-tools/blob/d8dc1ac173ceb85776b3dc87c12acea234c96079/data/projects.toml), for example, which is a single flat file.


> I believe this is the right direction to go for maintainability.

Great! I think so, too.

> I would also propose that we have deep links into the individual language sub-directories to have a high level summary in the property table in the root readme, but more in-depth examples, summaries, thoughts, status etc. in the individual config.

This sounds like a lot of initial work and ongoing maintenance. Links rot quickly (<https://gwern.net/archiving#link-rot> is a fascinating and bleak read), examples and analyses need updating, especially for new litter languages. It would be a major expansion in project scope. I won't commit to it.

> Aside: I would also like to add a strict "status" to possibly allow hobby projects or projects just getting started a chance to list their work and bring interest and not muddy the waters of more fleshed out projects that folks may be looking to incorporate into their own projects.

This sounds like a good idea, and I am in favor of it, though I don't want to implement it myself. It could help hobbyists, even if they don't adopt each other's languages. You are welcome to implement it after the switch.

> I prefer TOML personally (and have written my own config language based on it), but JSON + TS is so ubiquitous it is a great choice simply for lowering the barrier to entry.

Let's go with TOML. I also prefer it to YAML and JSON. With TOML, we can store all projects in one file or in separate files. One big file has the advantage of instantly giving you examples when you edit. With JSON, one big file would be error-prone to work with. I think contributors can adapt to TOML quickly, and then it will be easier for them than JSON.

**Comment by dbohdan** [comment]
Okay, that's two people in favor of JS/TS. I'll take it into account. Note that contributors won't need to touch the generator code for routine updates, only run it after changing the data. Also note that we aren't voting. (I understand that you  probably weren't suggesting we were, but just to make things clear.) I will decide based on my evaluation while considering your opinions.

**Comment by mwasplund** [comment]
> It would be a major expansion in project scope. 

I realize scope increase is a major concern. I was simply proposing that we create a two tiered approach to the information for a high level summary in the root readme for quick searching with links to a more detailed markdown for each language in the same repo. This would allow for slow focused increases to the scope over time without creating an hard to consume root readme. It also lends itself nicely to having a script scan folder structure which also has the benefit to not requiring a large single config file that can be hard to maintain. Just my opinions, feel free to do what you think is best 👍 

> Also note that we aren't voting.

By "vote" I meant my opinion. I agree this is the right direction and as long as the process for regenerating is easy and well documented I have no concerns.

**Comment by dbohdan** [comment]
﻿> I was simply proposing that we create a two tiered approach to the information for a high level summary in the root readme for quick searching with links to a more detailed markdown for each language in the same repo.

This is an interesting idea, and I can see its potential. That said, I don't want to handle even a gradual and compartmentalized increase in scope for as long as I am the primary maintainer. If you start a repo with auxiliary information about the projects here, I'll be happy to have a link to it.

> It also lends itself nicely to having a script scan folder structure which also has the benefit to not requiring a large single config file that can be hard to maintain.

I think a single large config file has its strengths as long as it is just one type of item repeated many times, like a database table. It is its own example doc. A large heterogeneous config is far less fun, but we won't have one regardless of the design choices we are discussing.

> Just my opinions, feel free to do what you think is best 👍

I do appreciate your opinions and feedback, @mwasplund and @paulocoghi. Without them, I might have decided people interested in this list wanted Lua.

> By "vote" I meant my opinion.

Sorry, I was replying to @paulocoghi, and I didn't make it clear. Anyway, I understand. I just want to leave no ambiguity about the process.

**Comment by dbohdan** [comment]
Solved via #80. Thanks for your feedback!
