### ISSUE TITLE
A BASIC dialect

### ISSUE THREAD

**Issue by paladin-t** [dbohdan/embedded-scripting-languages#8]
Consider adding [MY-BASIC](https://github.com/paladin-t/my_basic). Implemented with C. With Ref Count & Tracing GC.

**Comment by dbohdan** [comment]
I've given MY-BASIC a look and I would like to add it. First, however, I need to know how it combines RC with a tracing GC to describe it accurately and informatively in the list. Does it do something similar to what CPython does (RC + a tracing GC for cyclical references)? Are RC and the tracing GC used for different kinds of values?

**Comment by paladin-t** [comment]
Yes it does like CPython. RC and GC are used for the same referenced data types, including List, Dict, Prototype, Lambda Exp, Referenced Usertype; and maybe Array, depends on whether it's configurated as referenced.

**Comment by dbohdan** [comment]
All right. I've add MY-BASIC with 1725799.

**Comment by paladin-t** [comment]
Thanks!
