### ISSUE TITLE
Add Asp

### ISSUE THREAD

**Issue by allenbtaylor** [dbohdan/embedded-scripting-languages#85]
Asp is a Python-like scripting platform specifically designed for embedded systems.
https://www.asplang.org/
https://bitbucket.org/asplang

Implementation language: C
GC: None (static memory; ref counting within that)
License: Public domain
Notes:
- Python-like.
- Static allocation for script code and data memory spaces.
- Implementation does not use recursion.
- Leaves application in control of processor at high frequency.
- Allows blocking calls in scripts without blocking the application.
- Bare-metal or OS-based applications.
- Scripts must be compiled, binary version is run on the target.

**Comment by allenbtaylor** [comment]
The entry looks great...Thank you!
Blessings,
Allen

**Comment by dbohdan** [comment]
You're welcome!

**Comment by dbohdan** [comment]
You're welcome!
