### ISSUE TITLE
Add Nickel

### ISSUE THREAD

**Issue by ad-si** [dbohdan/embedded-scripting-languages#90]
https://nickel-lang.org

**Comment by dbohdan** [comment]
https://github.com/tweag/nickel/issues/1453#issuecomment-1643997366 from 2023 says:

> Unfortunately, the nickel-core library is indeed currently a bit provided "as it is" without much guidance nor backward-compatibility guarantee. I must say that it's not currently a high priority to work on that front. However, there might still be small effort improvements we can make.

Is it ready for embedding?

**Comment by ad-si** [comment]
Yes, it works with https://docs.rs/nickel-lang-core/latest/nickel_lang_core/
Just tried it out myself.
Basically:
`Program::new_from_file()`
-> `prog.eval_full_for_export()`
-> `serialize::to_string()`
